ALTER TABLE public.sirkulasi
ALTER COLUMN tanggal_pinjam TYPE TIMESTAMP WITH TIME ZONE USING tanggal_pinjam::TIMESTAMP WITH TIME ZONE,
ALTER COLUMN tanggal_dikembalikan TYPE TIMESTAMP WITH TIME ZONE USING tanggal_dikembalikan::TIMESTAMP WITH TIME ZONE;